### ISSUE TITLE
how to generate the files  as getchr33.20000.fill.mat.gz?

### ISSUE THREAD

**Issue by tan5251** [JiamanZhang/Lab_GCs_paper_codes#1]
how to generate the files  as getchr33.20000.fill.mat.gz?

**Comment by JiamanZhang** [comment]
Hi, you can use JuicerTools (https://github.com/aidenlab/juicer/wiki/Pre) to generate the similar contact matrix files.

**Comment by tan5251** [comment]
Hi. Thanks for your quicky reply. Sorry, we donot fully understand. I have .hic, cool/mcool and hicpro format. Your link is used to generate .hic files ? The file "getchr33.20000.fill.mat.gz" is not .hic format, right?

**Comment by JiamanZhang** [comment]
You can dump contact matrix from .hic files (using codes: java -Xmx20g -jar $ind/juicer_tools.1.8.9_jcuda.0.8.jar dump).

**Comment by tan5251** [comment]
Got it! Thanks so mush!
