### ISSUE TITLE
TADs analysis

### ISSUE THREAD

**Issue by zcq23** [JiamanZhang/Lab_GCs_paper_codes#3]
Hi, I would like to know what the specific process of TADs analysis is like, because although you have uploaded some of the code related to TADs, how some input files are obtained, and how the DI algorithm should be used (the existing DI algorithm I found is domaincall_software in PSYCHIC, but the instructions make me confused), thank you veryyyyyyyyyyyyyyyyyyyy much, please😭

**Comment by JiamanZhang** [comment]
Hi, the DI algorithm for TAD identification were obtained from Dixon, Nature, 2012 (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3356448/). And, the domaincall_software in PSYCHIC (for hierarchy TADs) is for identificatiion of promoter-enhancer interactions.

**Comment by zcq23** [comment]
> Hi, the DI algorithm for TAD identification were obtained from Dixon, Nature, 2012 (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3356448/). And, the domaincall_software in PSYCHIC (for hierarchy TADs) is for identificatiion of promoter-enhancer interactions.

It seems that the article only introduced the principle of DI algorithm, but did not give the corresponding analysis code😭I do not know that you have the relevant code, can generate DI score file and the subsequent input HMM to identify TADs and calculate IS score? Thank you very much indeed!

**Comment by JiamanZhang** [comment]
OK, you can get the original public code of the DomainCaller in http:// bioinformatics-renlab.ucsd.edu/collaborations/sid/domaincall_software.zip and download the public code related to IS score (matrix2insulation.pl, https:// github.com/dekkerlab/cworld-dekker). And, more details for identification of TADs could be seen in Methods sections in https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8917667/.

**Comment by JiamanZhang** [comment]
OK, you can get the original public code of the DomainCaller in http://bioinformatics-renlab.ucsd.edu/collaborations/sid/domaincall_software.zip and download the public code related to IS score (matrix2insulation.pl, https://github.com/dekkerlab/cworld-dekker). And, more details for identification of TADs could be seen in Methods sections in https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8917667/.

**Comment by zcq23** [comment]
> OK, you can get the original public code of the DomainCaller in http://bioinformatics-renlab.ucsd.edu/collaborations/sid/domaincall_software.zip and download the public code related to IS score (matrix2insulation.pl, https://github.com/dekkerlab/cworld-dekker). And, more details for identification of TADs could be seen in Methods sections in https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8917667/.

Thank you very much for your quick reply, which was very encouraging and helpful to me. But I find that http://bioinformatics-renlab.ucsd.edu/collaborations/sid/domaincall_software.zip has 404 not found, I was wondering if you had encountered this kind of situation? Please, thank you really so much!!

**Comment by JiamanZhang** [comment]
Sorry for the delayed reply! You can try using this tool: [DomainCaller](https://github.com/XiaoTaoWang/domaincaller).

**Comment by zcq23** [comment]
> Sorry for the delayed reply! You can try using this tool: [DomainCaller](https://github.com/XiaoTaoWang/domaincaller).

ohhhhhhhhhhhhhh yes sir! I will try it as you suggested! Thanks for your reply and suggestion, hope you a wonderful day!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
